[database]
host = "127.0.0.1"
port = "5432"
name = "stock_data"
user = "admin"
password = "password123"

[ai]
api_keys = [
    "AIzaSyCkZ_wy8mHH3puLji5CkUUu6pEvwbyE8sE", 
    "AIzaSyDIOXsDH0GJNqW37WEPwRfu8wxwmTQY2C4"
]
proxy_url = "http://127.0.0.1:7890"

[network]
quote_api_host = "183.136.160.11"
